### ISSUE TITLE
QP-decoding of continuation line header fields

### ISSUE THREAD

**Issue by gueriksson** [retupmoca/p6-Email-MIME#11]
Normal one-line header fields are decoded correctly by header-str method, but multi-line fields like the example below get no decoding at all:

`X-Gmail-Labels: =?UTF-8?Q?Arkiverat,Viktigt,=C3=96ppnat,Kategorin_Pe?=
   =?UTF-8?Q?rsonligt,jubbered/textred,BG,jubbered?=`

It seems like the grammar in `Email::MIME::Header` doesn't allow multiple occurrences of MIME-header strings.

**Comment by gueriksson** [comment]
The example again:
A newline and some spaces before the second MIME-string

**Comment by rbt** [comment]
So like this?
```
X-Gmail-Labels: =?UTF-8?Q?Arkiverat,Viktigt,=C3=96ppnat,Kategorin_Pe?= 
        =?UTF-8?Q?rsonligt,jubbered/textred,BG,jubbered?=
```

Looking at RFC1342, Email::Mime is missing a couple of tricks. In addition to your example, it also fails to handle encoded words intermixed with non-encoded words.

I'll see if I can fix that. Thank-you for the bug report.

**Comment by gueriksson** [comment]
Thanks! Yes, your version of the split is what I tried to achieve.

Note that the "original" field has been split in the middle of a label (don't know if this is according to the RFC).  After decoding the result ought to be:

`... ,Kategorin_Personligt, ...`

**Comment by rbt** [comment]
I created branch  f.multi-encoded-header  with a non-trivial reworked grammar. If you would be able to test it out and see if it works on other emails you have that would be appreciated.

I poked through my own accounts and found very few samples of encoded headers.

Otherwise, I'll push it out and see if anyone reports breaks.

**Comment by gueriksson** [comment]
Unfortunally, I couldn't find any other suitable email in my mailbox, other than the collection I am workning on, and all of them have header fields much like the example. But for all of them the decoding worked! So thanks a lot for your effort!
