### ISSUE TITLE
Content-Type: text/plain; charset=iso-8859-1

### ISSUE THREAD

**Issue by coke** [retupmoca/p6-Email-MIME#14]
Because the new() method is taking a Str, can't process non-utf8 emails directly. Might be worth adding a note to the 'new' documentation that mentions if you get an error processing non-utf8 file source, it might be worth using this syntax:

```
        my $msg = Email::MIME.new($file.IO.slurp: enc => 'utf8-c8');
```

at least as a stopgap (probably want to use the actual encoding defined in the file)

**Comment by rbt** [comment]
Thank-you. Removing that limitation requires changes to Email::Simple (which I don't have a commit bit for) and might require grammar for blobs to implement nicely.
